version: "3"
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - "8000:8000"
    networks:
      - security-portal
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "3000:3000"
    networks:
      - security-portal
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - security-portal
    volumes:
    - mongo-data:/data/db
networks:
  security-portal:
    driver: bridge
volumes:
  mongo-data:
    driver: local